Exellent_Taste.WEB/Controllers/ReseveringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Exellent_Taste.Models;
using Exellent_Taste.BUS.Interface;

namespace Exellent_Taste.WEB.Controllers
{
    public class ReseveringController : Controller
    {
        private readonly IReseveringenService _ReseveringenService;
        private readonly IBlackListService _BlackListService;
        private readonly IBestellingenService _BestellingenService;


        public ReseveringController(IReseveringenService ReseveringenService, IBlackListService blackListService, IBestellingenService BestellingenService)
        {
            _ReseveringenService = ReseveringenService;
            _BlackListService = blackListService;
            _BestellingenService = BestellingenService;
        }

        // GET: Resevering
        public async Task<IActionResult> Index()
        {
            var Model = await _ReseveringenService.GetAll();
            return View(Model);
        }

        // GET: Resevering/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var resevering = await _ReseveringenService.GetById(id);
            if (resevering == null)
            {
                return NotFound();
            }

            return View(resevering);
        }

        // GET: Resevering/Create
        public IActionResult Create()
        {
            Reseveringen resevering = new Reseveringen()
            {
                Adress = new Adress()
            };
            return View(resevering);
        }

        // POST: Resevering/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Reseveringen Model)
        {
            if (ModelState.IsValid)
            {
                //var Blacklist = await _BlackListService.GetByEmail(Model.Email);
                if (true)
                {
                    await _ReseveringenService.Create(Model);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    //ModelState.AddModelError("gekomenError", "Deze klant is een keer niet gekomen zonder aftezeggen");
                }
            }
            return View(Model);
        }

        // GET: Resevering/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var resevering = await _ReseveringenService.GetById(id);
            if (resevering == null)
            {
                return NotFound();
            }
            return View(resevering);
        }

        // POST: Resevering/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Reseveringen Model)
        {
            if (id != Model.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var resevering = await _ReseveringenService.GetById(id);
                if (resevering != null)
                {
                    await _ReseveringenService.Edit(Model);
                }
                else
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(Model);
        }

        // GET: Resevering/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var resevering = await _ReseveringenService.GetById(id);
            if (resevering == null)
            {
                return NotFound();
            }
            return View(resevering);
        }

        // POST: DeleteConfirmed
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
 
                var resevering = await _ReseveringenService.GetById(id);
                if (resevering != null)
                {
                    await _ReseveringenService.Delete(resevering);
                }
                else
                {
                    return NotFound();
                }
            return RedirectToAction(nameof(Index));
        }
        // GET: Bestelling/Delete/5
        public async Task<IActionResult> Bestelling(int _id, int _Resevering, int _Tafel)
        {
            if (_id == 0)
            {
                var model = new Bestellingen()
                {
                    Tafel = _Tafel,
                };
                var bestelling = await _BestellingenService.Create(model);
                var resevering = await _ReseveringenService.GetById(_Resevering);
                resevering.Bestelling_id = bestelling.ID;
                await _ReseveringenService.Edit(resevering);

                return RedirectToAction("Details", "Bestellings", new { id = bestelling.ID });
            }
            else
            {
                return RedirectToAction("Details", "Bestellings", new { id = _id });
            }

        }

        private bool ReseveringenExists(int id)
        {
            if (_ReseveringenService.GetById(id) != null)
            {   return true;    }
            else { return false; }
        }
    }
}

Exellent_Taste.WEB/Views/Resevering/Create.cshtml
@model Exellent_Taste.Models.Reseveringen

@{
    ViewData["Title"] = "Resevering aanmaken";
}
<hr />
<form asp-action="Create">
    <div class="row">
        <div class="col">

            <div class="form-row">
                @Html.AntiForgeryToken()
                @Html.ValidationMessage("gekomenError")
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-md-6">
                    <label asp-for="Voornaam" class="control-label"></label>
                    <input asp-for="Voornaam" class="form-control" />
                    <span asp-validation-for="Voornaam" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Achternaam" class="control-label"></label>
                    <input asp-for="Achternaam" class="form-control" />
                    <span asp-validation-for="Achternaam" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Telefoonnummer" class="control-label"></label>
                    <input asp-for="Telefoonnummer" class="form-control" />
                    <span asp-validation-for="Telefoonnummer" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Adress.Straat" class="control-label"></label>
                    <input asp-for="Adress.Straat" class="form-control" />
                    <span asp-validation-for="Adress.Straat" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Adress.Huisnummer" class="control-label"></label>
                    <input asp-for="Adress.Huisnummer" class="form-control" />
                    <span asp-validation-for="Adress.Huisnummer" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Adress.Toevoeging" class="control-label"></label>
                    <input asp-for="Adress.Toevoeging" class="form-control" />
                    <span asp-validation-for="Adress.Toevoeging" class="text-danger"></span>
                </div>

            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Adress.Stad" class="control-label"></label>
                    <input asp-for="Adress.Stad" class="form-control" />
                    <span asp-validation-for="Adress.Stad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Adress.Land" class="control-label"></label>
                    <input asp-for="Adress.Land" class="form-control" />
                    <span asp-validation-for="Adress.Land" class="text-danger"></span>
                </div>
                <div class="form-group col-md-2">
                    <label asp-for="Adress.Postcode" class="control-label"></label>
                    <input asp-for="Adress.Postcode" class="form-control" />
                    <span asp-validation-for="Adress.Postcode" class="text-danger"></span>
                </div>
            </div>



        </div>
        <div class="col">

            <div class="form-group">
                <label asp-for="Tafel" class="control-label"></label>
                <input asp-for="Tafel" class="form-control" />
                <span asp-validation-for="Tafel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aantal_Personen" class="control-label"></label>
                <input asp-for="Aantal_Personen" class="form-control" />
                <span asp-validation-for="Aantal_Personen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tijd" class="control-label"></label>
                <input asp-for="Tijd" class="form-control" />
                <span asp-validation-for="Tijd" class="text-danger"></span>
            </div>
        </div>

    </div>


    <div>
        <a asp-action="Index">Terug</a>
        <button type="submit" class="btn btn-primary">aanmaken</button>
    </div>
</form>

Exellent_Taste.WEB/Views/Resevering/Delete.cshtml
@model Exellent_Taste.Models.Reseveringen

@{
    ViewData["Title"] = "Resevering verwijderen";
}
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Voornaam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Voornaam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Achternaam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Achternaam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefoonnummer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefoonnummer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tafel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tafel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Aantal_Personen)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Aantal_Personen)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tijd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tijd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gekomen)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gekomen)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Terug</a>
    </form>
</div>

Exellent_Taste.WEB/Views/Resevering/Details.cshtml
@model Exellent_Taste.Models.Reseveringen

@{
    ViewData["Title"] = "Resevering details";
}

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Voornaam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Voornaam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Achternaam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Achternaam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefoonnummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefoonnummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aantal_Personen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aantal_Personen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tijd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tijd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gekomen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gekomen)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Bijwerken</a> |
    <a asp-action="Index">Terug</a>
</div>

Exellent_Taste.WEB/Views/Resevering/Edit.cshtml
@model Exellent_Taste.Models.Reseveringen

@{
    ViewData["Title"] = "Resevering bijwerken";
}
<hr />
<form asp-action="Edit">
    <div class="row">
        <div class="col">
            <div class="form-row">
                @Html.AntiForgeryToken()
                @Html.ValidationMessage("gekomenError")
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-md-6">
                    <label asp-for="Voornaam" class="control-label"></label>
                    <input asp-for="Voornaam" class="form-control" />
                    <span asp-validation-for="Voornaam" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Achternaam" class="control-label"></label>
                    <input asp-for="Achternaam" class="form-control" />
                    <span asp-validation-for="Achternaam" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Telefoonnummer" class="control-label"></label>
                    <input asp-for="Telefoonnummer" class="form-control" />
                    <span asp-validation-for="Telefoonnummer" class="text-danger"></span>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Adress.Straat" class="control-label"></label>
                    <input asp-for="Adress.Straat" class="form-control" />
                    <span asp-validation-for="Adress.Straat" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Adress.Huisnummer" class="control-label"></label>
                    <input asp-for="Adress.Huisnummer" class="form-control" />
                    <span asp-validation-for="Adress.Huisnummer" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="Adress.Toevoeging" class="control-label"></label>
                    <input asp-for="Adress.Toevoeging" class="form-control" />
                    <span asp-validation-for="Adress.Toevoeging" class="text-danger"></span>
                </div>

            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Adress.Stad" class="control-label"></label>
                    <input asp-for="Adress.Stad" class="form-control" />
                    <span asp-validation-for="Adress.Stad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Adress.Land" class="control-label"></label>
                    <input asp-for="Adress.Land" class="form-control" />
                    <span asp-validation-for="Adress.Land" class="text-danger"></span>
                </div>
                <div class="form-group col-md-2">
                    <label asp-for="Adress.Postcode" class="control-label"></label>
                    <input asp-for="Adress.Postcode" class="form-control" />
                    <span asp-validation-for="Adress.Postcode" class="text-danger"></span>
                </div>
            </div>



        </div>
        <div class="col">

            <div class="form-group">
                <label asp-for="Tafel" class="control-label"></label>
                <input asp-for="Tafel" class="form-control" />
                <span asp-validation-for="Tafel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aantal_Personen" class="control-label"></label>
                <input asp-for="Aantal_Personen" class="form-control" />
                <span asp-validation-for="Aantal_Personen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tijd" class="control-label"></label>
                <input asp-for="Tijd" class="form-control" />
                <span asp-validation-for="Tijd" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Gekomen" /> @Html.DisplayNameFor(model => model.Gekomen)
                </label>
            </div>
        </div>

    </div>
    <div>
        <a asp-action="Index">Terug</a>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</form>

Exellent_Taste.WEB/Views/Resevering/Index.cshtml
@model IEnumerable<Exellent_Taste.Models.Reseveringen>

@{
    ViewData["Title"] = "Overzicht reseveringen";
}

    <div class="card mb-4">
        <a class="card-header" asp-action="Create"><i class="fas fa-table mr-1"></i>Create New</a>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Voornaam)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Achternaam)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Telefoonnummer)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Aantal_Personen)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Datum)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Tijd)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Gekomen)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Voornaam)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Achternaam)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefoonnummer)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Aantal_Personen)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Datum)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tijd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Gekomen)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                                <a asp-action="Bestelling" asp-route-_id="@item.Bestelling_id" asp-route-_Resevering="@item.ID" asp-route-_Tafel="@item.Tafel"  >Bestelling</a> |
                                <a  asp-action="DeleteConfirmed" asp-controller="Resevering" asp-route-id="@item.ID"><i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>